name: animated_loading_button
description: A new flutter button with built-in animations, customizable design and async callback.
version: 1.0.0
homepage: https://github.com/koukibadr/Animated_Loading_Button

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

